#
# Prompt-wide configuration options
#

# Inserts a blank line between shell prompts
add_newline = false


#
# First row: info & current status
#

[username]
format = "[$user]($style) "
style_user = "bold cyan"
style_root = "bold red"
show_always = true

[hostname]
format = "at [$hostname]($style) "
style = "bold cyan"
ssh_only = true

[directory]
format = "in [$path]($style)[$read_only]($style) "
style = "bold purple"
read_only = ":ro"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

[git_status]
style = "bold purple"
ahead = "${count}"
diverged = "${ahead_count}⇣${behind_count}"
behind = "${count}"
deleted = "x"

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "
style = "purple"

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true
pyenv_prefix = ""

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[cmd_duration]
style = "bold green"
min_time = 1
format = "took [$duration]($style)"
disabled = false


#
# Second row: prompt
#

[battery]
disabled = true

[time]
disabled = true

[character]
success_symbol = "[λ](purple)"
error_symbol = ""

[status]
format = '[$status $symbol]($style)'
style = "red"
symbol = "×"  # The symbol displayed on program error
not_executable_symbol = "×"  # The symbol displayed when file isn't executable
not_found_symbol = "?"  # The symbol displayed when the command can't be found
sigint_symbol = "!"  # The symbol displayed on SIGINT (Ctrl + c)
signal_symbol = ""  #	The symbol displayed on any signal
recognize_signal_code = true  # Enable signal mapping from exit code
map_symbol = true  # Enable symbols mapping from exit code
disabled = false
